name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: ./cypress/reports/html

  publish-to-gh-pages:
      needs: cypress-run
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          uses: actions/checkout@v4                
        - name: Create and clean gh-pages branch
          continue-on-error: true
          run: |
            git checkout --orphan gh-pages
            git rm -rf . 
                  
        - name: Download Cypress artifacts
          uses: actions/download-artifact@v3
          with:
            name: build
            path: ./cypress/reports/html
                  
        - name: Deploy report to Github Pages
          if: always()
          uses: peaceiris/actions-gh-pages@v2
          env:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: ./cypress/reports/html